// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEconomyShopItems(t *testing.T) {
	t.Parallel()

	query := EconomyShopItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEconomyShopItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyShopItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EconomyShopItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyShopItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EconomyShopItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyShopItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EconomyShopItemExists(ctx, tx, o.GuildID, o.LocalID)
	if err != nil {
		t.Errorf("Unable to check if EconomyShopItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EconomyShopItemExists to return true, but got false.")
	}
}

func testEconomyShopItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	economyShopItemFound, err := FindEconomyShopItem(ctx, tx, o.GuildID, o.LocalID)
	if err != nil {
		t.Error(err)
	}

	if economyShopItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEconomyShopItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EconomyShopItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEconomyShopItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EconomyShopItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEconomyShopItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	economyShopItemOne := &EconomyShopItem{}
	economyShopItemTwo := &EconomyShopItem{}
	if err = randomize.Struct(seed, economyShopItemOne, economyShopItemDBTypes, false, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}
	if err = randomize.Struct(seed, economyShopItemTwo, economyShopItemDBTypes, false, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = economyShopItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = economyShopItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EconomyShopItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEconomyShopItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	economyShopItemOne := &EconomyShopItem{}
	economyShopItemTwo := &EconomyShopItem{}
	if err = randomize.Struct(seed, economyShopItemOne, economyShopItemDBTypes, false, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}
	if err = randomize.Struct(seed, economyShopItemTwo, economyShopItemDBTypes, false, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = economyShopItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = economyShopItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testEconomyShopItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEconomyShopItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(economyShopItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEconomyShopItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEconomyShopItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EconomyShopItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEconomyShopItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EconomyShopItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	economyShopItemDBTypes = map[string]string{`GuildID`: `bigint`, `LocalID`: `bigint`, `Icon`: `text`, `Name`: `text`, `RoleID`: `bigint`, `GamblingBoostPercentage`: `integer`, `Cost`: `bigint`, `Type`: `smallint`}
	_                      = bytes.MinRead
)

func testEconomyShopItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(economyShopItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(economyShopItemColumns) == len(economyShopItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEconomyShopItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(economyShopItemColumns) == len(economyShopItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopItem{}
	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, economyShopItemDBTypes, true, economyShopItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(economyShopItemColumns, economyShopItemPrimaryKeyColumns) {
		fields = economyShopItemColumns
	} else {
		fields = strmangle.SetComplement(
			economyShopItemColumns,
			economyShopItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EconomyShopItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEconomyShopItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(economyShopItemColumns) == len(economyShopItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EconomyShopItem{}
	if err = randomize.Struct(seed, &o, economyShopItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EconomyShopItem: %s", err)
	}

	count, err := EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, economyShopItemDBTypes, false, economyShopItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyShopItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EconomyShopItem: %s", err)
	}

	count, err = EconomyShopItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
