// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEconomyShopListItems(t *testing.T) {
	t.Parallel()

	query := EconomyShopListItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEconomyShopListItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyShopListItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EconomyShopListItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyShopListItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EconomyShopListItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyShopListItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EconomyShopListItemExists(ctx, tx, o.GuildID, o.LocalID)
	if err != nil {
		t.Errorf("Unable to check if EconomyShopListItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EconomyShopListItemExists to return true, but got false.")
	}
}

func testEconomyShopListItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	economyShopListItemFound, err := FindEconomyShopListItem(ctx, tx, o.GuildID, o.LocalID)
	if err != nil {
		t.Error(err)
	}

	if economyShopListItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEconomyShopListItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EconomyShopListItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEconomyShopListItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EconomyShopListItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEconomyShopListItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	economyShopListItemOne := &EconomyShopListItem{}
	economyShopListItemTwo := &EconomyShopListItem{}
	if err = randomize.Struct(seed, economyShopListItemOne, economyShopListItemDBTypes, false, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}
	if err = randomize.Struct(seed, economyShopListItemTwo, economyShopListItemDBTypes, false, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = economyShopListItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = economyShopListItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EconomyShopListItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEconomyShopListItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	economyShopListItemOne := &EconomyShopListItem{}
	economyShopListItemTwo := &EconomyShopListItem{}
	if err = randomize.Struct(seed, economyShopListItemOne, economyShopListItemDBTypes, false, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}
	if err = randomize.Struct(seed, economyShopListItemTwo, economyShopListItemDBTypes, false, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = economyShopListItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = economyShopListItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testEconomyShopListItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEconomyShopListItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(economyShopListItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEconomyShopListItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEconomyShopListItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EconomyShopListItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEconomyShopListItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EconomyShopListItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	economyShopListItemDBTypes = map[string]string{`GuildID`: `bigint`, `LocalID`: `bigint`, `ListID`: `bigint`, `Value`: `text`, `PurchasedBy`: `bigint`}
	_                          = bytes.MinRead
)

func testEconomyShopListItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(economyShopListItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(economyShopListItemAllColumns) == len(economyShopListItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEconomyShopListItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(economyShopListItemAllColumns) == len(economyShopListItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EconomyShopListItem{}
	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, economyShopListItemDBTypes, true, economyShopListItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(economyShopListItemAllColumns, economyShopListItemPrimaryKeyColumns) {
		fields = economyShopListItemAllColumns
	} else {
		fields = strmangle.SetComplement(
			economyShopListItemAllColumns,
			economyShopListItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EconomyShopListItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEconomyShopListItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(economyShopListItemAllColumns) == len(economyShopListItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EconomyShopListItem{}
	if err = randomize.Struct(seed, &o, economyShopListItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EconomyShopListItem: %s", err)
	}

	count, err := EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, economyShopListItemDBTypes, false, economyShopListItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyShopListItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EconomyShopListItem: %s", err)
	}

	count, err = EconomyShopListItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
