// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEconomyPickImages2s(t *testing.T) {
	t.Parallel()

	query := EconomyPickImages2s()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEconomyPickImages2sDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyPickImages2sQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EconomyPickImages2s().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyPickImages2sSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EconomyPickImages2Slice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEconomyPickImages2sExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EconomyPickImages2Exists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if EconomyPickImages2 exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EconomyPickImages2Exists to return true, but got false.")
	}
}

func testEconomyPickImages2sFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	economyPickImages2Found, err := FindEconomyPickImages2(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if economyPickImages2Found == nil {
		t.Error("want a record, got nil")
	}
}

func testEconomyPickImages2sBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EconomyPickImages2s().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEconomyPickImages2sOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EconomyPickImages2s().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEconomyPickImages2sAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	economyPickImages2One := &EconomyPickImages2{}
	economyPickImages2Two := &EconomyPickImages2{}
	if err = randomize.Struct(seed, economyPickImages2One, economyPickImages2DBTypes, false, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}
	if err = randomize.Struct(seed, economyPickImages2Two, economyPickImages2DBTypes, false, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = economyPickImages2One.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = economyPickImages2Two.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EconomyPickImages2s().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEconomyPickImages2sCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	economyPickImages2One := &EconomyPickImages2{}
	economyPickImages2Two := &EconomyPickImages2{}
	if err = randomize.Struct(seed, economyPickImages2One, economyPickImages2DBTypes, false, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}
	if err = randomize.Struct(seed, economyPickImages2Two, economyPickImages2DBTypes, false, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = economyPickImages2One.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = economyPickImages2Two.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testEconomyPickImages2sInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEconomyPickImages2sInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(economyPickImages2ColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEconomyPickImages2sReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEconomyPickImages2sReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EconomyPickImages2Slice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEconomyPickImages2sSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EconomyPickImages2s().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	economyPickImages2DBTypes = map[string]string{`ID`: `bigint`, `GuildID`: `bigint`, `Image`: `bytea`}
	_                         = bytes.MinRead
)

func testEconomyPickImages2sUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(economyPickImages2PrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(economyPickImages2AllColumns) == len(economyPickImages2PrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2PrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEconomyPickImages2sSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(economyPickImages2AllColumns) == len(economyPickImages2PrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EconomyPickImages2{}
	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2ColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, economyPickImages2DBTypes, true, economyPickImages2PrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(economyPickImages2AllColumns, economyPickImages2PrimaryKeyColumns) {
		fields = economyPickImages2AllColumns
	} else {
		fields = strmangle.SetComplement(
			economyPickImages2AllColumns,
			economyPickImages2PrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EconomyPickImages2Slice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEconomyPickImages2sUpsert(t *testing.T) {
	t.Parallel()

	if len(economyPickImages2AllColumns) == len(economyPickImages2PrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EconomyPickImages2{}
	if err = randomize.Struct(seed, &o, economyPickImages2DBTypes, true); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EconomyPickImages2: %s", err)
	}

	count, err := EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, economyPickImages2DBTypes, false, economyPickImages2PrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EconomyPickImages2 struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EconomyPickImages2: %s", err)
	}

	count, err = EconomyPickImages2s().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
