// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("EconomyConfigs", testEconomyConfigsUpsert)

	t.Run("EconomyLogs", testEconomyLogsUpsert)

	t.Run("EconomyPickImages2s", testEconomyPickImages2sUpsert)

	t.Run("EconomyPlants", testEconomyPlantsUpsert)

	t.Run("EconomyShopItems", testEconomyShopItemsUpsert)

	t.Run("EconomyShopListItems", testEconomyShopListItemsUpsert)

	t.Run("EconomyUsers", testEconomyUsersUpsert)

	t.Run("EconomyWaifuItems", testEconomyWaifuItemsUpsert)
}
